# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        script:
          - git remote add heroku https://git.heroku.com/phamonis.git
    - step:
        name: Deploy to Heroku
        deployment: staging   # can be test, staging or production.
      # trigger: manual  # Uncomment to make this a manual deployment.
        script:
        - git add .
        - git commit -m "push to heroku"
        - git push heroku master
